"""
HTML export formatter for Stride sprint data.

Exports sprint data as styled HTML reports with interactive elements,
progress charts, and navigation between sprints.
"""

from typing import Any, Dict, List
from datetime import datetime
import html

from stride.export.export_engine import ExportFormatter


class HTMLFormatter(ExportFormatter):
    """HTML export formatter."""
    
    def __init__(self, theme: str = "default", include_styles: bool = True):
        """
        Initialize HTML formatter.
        
        Args:
            theme: CSS theme ('default', 'dark', 'minimal')
            include_styles: If True, include CSS in output
        """
        self.theme = theme
        self.include_styles = include_styles
    
    def format(self, sprints: List[Dict[str, Any]], metadata: Dict[str, Any]) -> str:
        """
        Format sprint data as HTML.
        
        Args:
            sprints: List of sprint data dictionaries
            metadata: Export metadata
            
        Returns:
            HTML-formatted string
        """
        lines = []
        
        # HTML header
        lines.append("<!DOCTYPE html>")
        lines.append("<html lang=\"en\">")
        lines.append("<head>")
        lines.append("    <meta charset=\"UTF-8\">")
        lines.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
        lines.append("    <title>Sprint Export Report</title>")
        
        # Include CSS if requested
        if self.include_styles:
            lines.append("    <style>")
            lines.append(self._get_css())
            lines.append("    </style>")
        
        lines.append("</head>")
        lines.append("<body>")
        lines.append("    <div class=\"container\">")
        
        # Header
        lines.append("        <header>")
        lines.append("            <h1>🏃 Sprint Export Report</h1>")
        lines.append(f"            <p class=\"timestamp\">Generated: {html.escape(metadata['timestamp'])}</p>")
        lines.append("        </header>")
        
        # Summary section
        lines.append("        <section class=\"summary\">")
        lines.append("            <h2>Summary</h2>")
        lines.append("            <div class=\"stats\">")
        lines.append(f"                <div class=\"stat-box\">")
        lines.append(f"                    <div class=\"stat-value\">{metadata['total_sprints']}</div>")
        lines.append(f"                    <div class=\"stat-label\">Total Sprints</div>")
        lines.append(f"                </div>")
        lines.append(f"                <div class=\"stat-box\">")
        lines.append(f"                    <div class=\"stat-value\">{metadata['exported_sprints']}</div>")
        lines.append(f"                    <div class=\"stat-label\">Exported Sprints</div>")
        lines.append(f"                </div>")
        lines.append("            </div>")
        lines.append("        </section>")
        
        # Filters section
        filters = metadata.get("filters", {})
        if any(v for v in filters.values()):
            lines.append("        <section class=\"filters\">")
            lines.append("            <h3>Filters Applied</h3>")
            lines.append("            <ul>")
            for key, value in filters.items():
                if value:
                    lines.append(f"                <li><strong>{html.escape(key.title())}:</strong> {html.escape(str(value))}</li>")
            lines.append("            </ul>")
            lines.append("        </section>")
        
        # Sprint list
        if sprints:
            lines.append("        <section class=\"sprints\">")
            lines.append("            <h2>Sprints</h2>")
            
            for sprint in sprints:
                lines.extend(self._format_sprint_html(sprint))
            
            lines.append("        </section>")
        else:
            lines.append("        <section class=\"no-sprints\">")
            lines.append("            <p>No sprints match the filter criteria.</p>")
            lines.append("        </section>")
        
        # Statistics section
        if sprints:
            lines.append("        <section class=\"statistics\">")
            lines.append("            <h2>Statistics</h2>")
            lines.extend(self._format_statistics_html(sprints))
            lines.append("        </section>")
        
        # Footer
        lines.append("        <footer>")
        lines.append("            <p>Generated by <strong>Stride Export</strong></p>")
        lines.append("        </footer>")
        
        lines.append("    </div>")
        lines.append("</body>")
        lines.append("</html>")
        
        return "\n".join(lines)
    
    def _format_sprint_html(self, sprint: Dict[str, Any]) -> List[str]:
        """Format a single sprint as HTML."""
        lines = []
        
        sprint_id = sprint["id"]
        metadata = sprint["metadata"]
        status = sprint["status"]
        
        # Sprint card
        lines.append(f"            <div class=\"sprint-card\" id=\"{html.escape(sprint_id.lower())}\">")
        
        # Header
        title = html.escape(metadata.get("title", "Untitled Sprint"))
        lines.append(f"                <div class=\"sprint-header\">")
        lines.append(f"                    <h3>{html.escape(sprint_id)}: {title}</h3>")
        lines.append(f"                    <span class=\"status-badge status-{html.escape(status)}\">{html.escape(status)}</span>")
        lines.append(f"                </div>")
        
        # Metadata
        lines.append(f"                <div class=\"sprint-metadata\">")
        
        if metadata.get("author"):
            lines.append(f"                    <div class=\"meta-item\"><strong>Author:</strong> {html.escape(metadata['author'])}</div>")
        if metadata.get("priority"):
            lines.append(f"                    <div class=\"meta-item\"><strong>Priority:</strong> {html.escape(metadata['priority'])}</div>")
        if metadata.get("created"):
            lines.append(f"                    <div class=\"meta-item\"><strong>Created:</strong> {html.escape(metadata['created'])}</div>")
        if metadata.get("tags"):
            tags_html = " ".join(f"<span class=\"tag\">{html.escape(tag)}</span>" for tag in metadata['tags'])
            lines.append(f"                    <div class=\"meta-item\"><strong>Tags:</strong> {tags_html}</div>")
        if metadata.get("agents"):
            agents_html = " ".join(f"<span class=\"agent\">{html.escape(agent)}</span>" for agent in metadata['agents'])
            lines.append(f"                    <div class=\"meta-item\"><strong>Agents:</strong> {agents_html}</div>")
        
        lines.append(f"                </div>")
        
        # Description
        if metadata.get("description"):
            desc = html.escape(metadata["description"]).replace("\n", "<br>")
            lines.append(f"                <div class=\"sprint-description\">")
            lines.append(f"                    <p>{desc}</p>")
            lines.append(f"                </div>")
        
        # Files
        files = sprint.get("files", {})
        if files:
            lines.append(f"                <div class=\"sprint-files\">")
            lines.append(f"                    <h4>Files</h4>")
            lines.append(f"                    <ul>")
            for file_name in sorted(files.keys()):
                content = files[file_name]
                if content:
                    word_count = len(content.split())
                    lines.append(f"                        <li class=\"file-exists\">✅ {html.escape(file_name)} ({word_count} words)</li>")
                else:
                    lines.append(f"                        <li class=\"file-empty\">⚠️  {html.escape(file_name)} (empty)</li>")
            lines.append(f"                    </ul>")
            lines.append(f"                </div>")
        
        # Timeline
        timeline = sprint.get("timeline", [])
        if timeline:
            lines.append(f"                <div class=\"sprint-timeline\">")
            lines.append(f"                    <h4>Activity ({len(timeline)} events)</h4>")
            lines.append(f"                    <ul class=\"timeline\">")
            
            # Show first 5 events
            for event in timeline[:5]:
                event_type = html.escape(event.get("event_type", "unknown"))
                timestamp = event.get("timestamp", "")
                
                try:
                    dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                    time_str = dt.strftime("%Y-%m-%d %H:%M")
                except:
                    time_str = timestamp
                
                lines.append(f"                        <li><span class=\"event-time\">{html.escape(time_str)}</span> - {event_type.replace('_', ' ').title()}</li>")
            
            if len(timeline) > 5:
                lines.append(f"                        <li class=\"more-events\">... {len(timeline) - 5} more events</li>")
            
            lines.append(f"                    </ul>")
            lines.append(f"                </div>")
        
        lines.append(f"            </div>")
        
        return lines
    
    def _format_statistics_html(self, sprints: List[Dict[str, Any]]) -> List[str]:
        """Format statistics section as HTML."""
        lines = []
        
        # Status distribution
        status_counts = {}
        for sprint in sprints:
            status = sprint["status"]
            status_counts[status] = status_counts.get(status, 0) + 1
        
        if status_counts:
            lines.append("            <div class=\"stat-table\">")
            lines.append("                <h3>Status Distribution</h3>")
            lines.append("                <table>")
            lines.append("                    <thead>")
            lines.append("                        <tr><th>Status</th><th>Count</th><th>Percentage</th></tr>")
            lines.append("                    </thead>")
            lines.append("                    <tbody>")
            
            total = len(sprints)
            for status, count in sorted(status_counts.items()):
                percentage = (count / total * 100) if total > 0 else 0
                lines.append(f"                        <tr>")
                lines.append(f"                            <td>{html.escape(status)}</td>")
                lines.append(f"                            <td>{count}</td>")
                lines.append(f"                            <td>{percentage:.1f}%</td>")
                lines.append(f"                        </tr>")
            
            lines.append("                    </tbody>")
            lines.append("                </table>")
            lines.append("            </div>")
        
        return lines
    
    def _get_css(self) -> str:
        """Get CSS stylesheet for the report."""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e0e0e0; }
        header h1 { color: #2c3e50; margin-bottom: 10px; }
        .timestamp { color: #7f8c8d; font-size: 0.9em; }
        .summary { margin-bottom: 30px; }
        .stats { display: flex; gap: 20px; margin-top: 20px; }
        .stat-box { flex: 1; background: #ecf0f1; padding: 20px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 2.5em; font-weight: bold; color: #3498db; }
        .stat-label { color: #7f8c8d; margin-top: 5px; }
        .filters { margin-bottom: 30px; padding: 20px; background: #fff8e1; border-left: 4px solid #ffc107; border-radius: 4px; }
        .filters ul { list-style: none; }
        .filters li { padding: 5px 0; }
        .sprint-card { margin-bottom: 30px; padding: 25px; background: #fafafa; border: 1px solid #e0e0e0; border-radius: 8px; }
        .sprint-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .sprint-header h3 { color: #2c3e50; }
        .status-badge { padding: 4px 12px; border-radius: 12px; font-size: 0.85em; font-weight: 600; text-transform: uppercase; }
        .status-proposed { background: #fff4e6; color: #e67e22; }
        .status-active { background: #e3f2fd; color: #2196f3; }
        .status-blocked { background: #ffebee; color: #e53935; }
        .status-review { background: #f3e5f5; color: #9c27b0; }
        .status-completed { background: #e8f5e9; color: #4caf50; }
        .sprint-metadata { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; margin-bottom: 15px; }
        .meta-item { padding: 8px 0; }
        .tag, .agent { display: inline-block; padding: 2px 8px; margin-right: 5px; background: #e0e0e0; border-radius: 3px; font-size: 0.85em; }
        .sprint-description { margin: 15px 0; padding: 15px; background: white; border-left: 3px solid #3498db; }
        .sprint-files, .sprint-timeline { margin-top: 15px; }
        .sprint-files h4, .sprint-timeline h4 { color: #34495e; margin-bottom: 10px; }
        .sprint-files ul, .timeline { list-style: none; padding-left: 10px; }
        .sprint-files li { padding: 5px 0; }
        .file-exists { color: #27ae60; }
        .file-empty { color: #e67e22; }
        .timeline li { padding: 5px 0; border-left: 2px solid #3498db; padding-left: 15px; margin-left: 5px; }
        .event-time { color: #7f8c8d; font-size: 0.9em; }
        .more-events { color: #7f8c8d; font-style: italic; }
        .statistics { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0e0e0; }
        .stat-table { margin-top: 20px; }
        .stat-table table { width: 100%; border-collapse: collapse; }
        .stat-table th, .stat-table td { padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }
        .stat-table th { background: #ecf0f1; font-weight: 600; }
        .no-sprints { padding: 40px; text-align: center; color: #7f8c8d; }
        footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0e0e0; text-align: center; color: #7f8c8d; }
        """
    
    def get_extension(self) -> str:
        """Get file extension for HTML format."""
        return "html"
