"""
Markdown export formatter for Stride sprint data.

Exports sprint data as readable Markdown reports with summaries,
progress tables, timeline sections, and formatted metadata.
"""

from typing import Any, Dict, List
from datetime import datetime

from stride.export.export_engine import ExportFormatter


class MarkdownFormatter(ExportFormatter):
    """Markdown export formatter."""
    
    def __init__(self, template: str = "default"):
        """
        Initialize Markdown formatter.
        
        Args:
            template: Template name ('default', 'technical', 'stakeholder')
        """
        self.template = template
    
    def format(self, sprints: List[Dict[str, Any]], metadata: Dict[str, Any]) -> str:
        """
        Format sprint data as Markdown.
        
        Args:
            sprints: List of sprint data dictionaries
            metadata: Export metadata
            
        Returns:
            Markdown-formatted string
        """
        lines = []
        
        # Header
        lines.append("# Sprint Export Report")
        lines.append("")
        lines.append(f"**Generated:** {metadata['timestamp']}")
        lines.append(f"**Format:** {metadata['format']}")
        lines.append(f"**Total Sprints:** {metadata['total_sprints']}")
        lines.append(f"**Exported Sprints:** {metadata['exported_sprints']}")
        lines.append("")
        
        # Filters summary
        filters = metadata.get("filters", {})
        if any(v for v in filters.values()):
            lines.append("## Filters Applied")
            lines.append("")
            for key, value in filters.items():
                if value:
                    lines.append(f"- **{key.title()}:** {value}")
            lines.append("")
        
        # Table of contents
        if sprints:
            lines.append("## Table of Contents")
            lines.append("")
            for i, sprint in enumerate(sprints, 1):
                sprint_id = sprint["id"]
                title = sprint["metadata"].get("title", "Untitled")
                lines.append(f"{i}. [{sprint_id}: {title}](#{sprint_id.lower()})")
            lines.append("")
        
        # Sprint summaries
        lines.append("## Sprint Summaries")
        lines.append("")
        
        if not sprints:
            lines.append("*No sprints match the filter criteria.*")
            lines.append("")
        else:
            for sprint in sprints:
                lines.extend(self._format_sprint_summary(sprint))
        
        # Statistics
        lines.append("---")
        lines.append("")
        lines.append("## Statistics")
        lines.append("")
        
        # Status distribution
        status_counts = {}
        for sprint in sprints:
            status = sprint["status"]
            status_counts[status] = status_counts.get(status, 0) + 1
        
        if status_counts:
            lines.append("### Status Distribution")
            lines.append("")
            lines.append("| Status | Count | Percentage |")
            lines.append("|--------|-------|------------|")
            total = len(sprints)
            for status, count in sorted(status_counts.items()):
                percentage = (count / total * 100) if total > 0 else 0
                lines.append(f"| {status} | {count} | {percentage:.1f}% |")
            lines.append("")
        
        # Priority distribution
        priority_counts = {}
        for sprint in sprints:
            priority = sprint["metadata"].get("priority", "unset")
            priority_counts[priority] = priority_counts.get(priority, 0) + 1
        
        if priority_counts:
            lines.append("### Priority Distribution")
            lines.append("")
            lines.append("| Priority | Count |")
            lines.append("|----------|-------|")
            for priority, count in sorted(priority_counts.items()):
                lines.append(f"| {priority} | {count} |")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Stride Export*")
        lines.append("")
        
        return "\n".join(lines)
    
    def _format_sprint_summary(self, sprint: Dict[str, Any]) -> List[str]:
        """Format a single sprint as Markdown."""
        lines = []
        
        sprint_id = sprint["id"]
        metadata = sprint["metadata"]
        status = sprint["status"]
        
        # Sprint header
        title = metadata.get("title", "Untitled Sprint")
        lines.append(f"### {sprint_id}: {title}")
        lines.append("")
        
        # Metadata table
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **ID** | {sprint_id} |")
        lines.append(f"| **Status** | {status} |")
        
        if metadata.get("author"):
            lines.append(f"| **Author** | {metadata['author']} |")
        if metadata.get("priority"):
            lines.append(f"| **Priority** | {metadata['priority']} |")
        if metadata.get("created"):
            lines.append(f"| **Created** | {metadata['created']} |")
        if metadata.get("updated"):
            lines.append(f"| **Updated** | {metadata['updated']} |")
        if metadata.get("tags"):
            tags_str = ", ".join(metadata['tags'])
            lines.append(f"| **Tags** | {tags_str} |")
        if metadata.get("agents"):
            agents_str = ", ".join(metadata['agents'])
            lines.append(f"| **Agents** | {agents_str} |")
        
        lines.append("")
        
        # Description
        if metadata.get("description"):
            lines.append("**Description:**")
            lines.append("")
            lines.append(metadata["description"])
            lines.append("")
        
        # Files summary
        files = sprint.get("files", {})
        if files:
            lines.append("**Files:**")
            lines.append("")
            for file_name in sorted(files.keys()):
                content = files[file_name]
                if content:
                    word_count = len(content.split())
                    lines.append(f"- ✅ {file_name} ({word_count} words)")
                else:
                    lines.append(f"- ⚠️  {file_name} (empty)")
            lines.append("")
        
        # Timeline summary
        timeline = sprint.get("timeline", [])
        if timeline:
            lines.append(f"**Activity:** {len(timeline)} events")
            lines.append("")
            
            # Show first 3 and last 3 events
            events_to_show = timeline[:3] if len(timeline) <= 6 else timeline[:3] + timeline[-3:]
            
            for event in events_to_show:
                event_type = event.get("event_type", "unknown")
                timestamp = event.get("timestamp", "")
                
                # Format timestamp
                try:
                    dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                    time_str = dt.strftime("%Y-%m-%d %H:%M")
                except:
                    time_str = timestamp
                
                lines.append(f"- *{time_str}* - {event_type.replace('_', ' ').title()}")
            
            if len(timeline) > 6:
                lines.append(f"- ... ({len(timeline) - 6} more events)")
            
            lines.append("")
        
        lines.append("---")
        lines.append("")
        
        return lines
    
    def get_extension(self) -> str:
        """Get file extension for Markdown format."""
        return "md"
